#!/usr/bin/python

import os,sys,os.path,string,re,shutil

def die(*args):
    print " ".join([str(x) for x in args])
    sys.exit(1)

with open("Dockerfile") as stream:
    for line in stream.readlines():
        line = line[:-1]
        print "#",line
        F = line.split()
        if len(F)<1: continue
        if line[0]=="#": continue
        if F[0] in ["FROM", "MAINTAINER"]:
            continue
        if F[0]=="RUN":
            status = os.system(line[4:])
            if status!=0: die("command failed")
            continue
        if F[0]=="ENV":
            os.environ[F[1]] = F[2]
            continue
        if F[0]=="ADD":
            shutil.copyfile(F[1], F[2])
            continue

